### ISSUE TITLE
How to check over file

### ISSUE THREAD

**Issue by Ankur008** [socomm/verify-email#1]
I have list of files(txt file) that contains the email, how should I use this script to check?

**Comment by Ankur008** [comment]
I have tried using this command while read in; do ./verify-email.py "$in"; done < /home/itstym/Desktop/email_database/sample.txt 

sample.txt

"baawd@aol.com"
"baawest@aol.com" 
"baawg13@aol.com" 
"baawg230@aol.com"

but end up getting the error

Traceback (most recent call last):
  File "./verify-email.py", line 32, in <module>
    server = (server[0]).split(' ')[1].rsplit('.', 1)[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "./verify-email.py", line 32, in <module>
    server = (server[0]).split(' ')[1].rsplit('.', 1)[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "./verify-email.py", line 32, in <module>
    server = (server[0]).split(' ')[1].rsplit('.', 1)[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "./verify-email.py", line 32, in <module>
    server = (server[0]).split(' ')[1].rsplit('.', 1)[0]
IndexError: list index out of range

**Comment by socomm** [comment]
Hey, Ankur, I've not implemented reading directly from a file on this script, however, you could loop over your file, assuming you are using bash, like so:

`for i in $(cat /home/itstym/Desktop/email_database/sample.txt); do ./verify-email.py "${i}" && printf "${i} is a valid e-mail address\n" || printf "${i} is not a valid email address\n"; done`

Just an example. You may need to tweak somethings to get it to work in your environment.

**Comment by Ankur008** [comment]
Hey, I tried using this way:

```
   while read in; 
	do 
	  ./verify-email.py "$in"; 
	done < /home/itstym/Desktop/email_database/sample.txt 
```

But whenever, I am using the loop, 
`server = (subprocess.check_output(['dig', '+short', domain,'MX'])).split('\n')`
return null. 
te
but if I tried it for the single item as ./verify-email.py email_name

it works fine.
